module.exports = [
  "Um feixe arcano explode na sua frente.",
  "Você sente uma energia ancestral percorrer seu corpo.",
  "Um portal interdimensional se abre atrás de você.",
  "Seu espírito é envolto em chamas místicas.",
  "Você invoca uma serpente feita de sombra pura.",
  "O tempo desacelera por um breve momento.",
  "Uma aura de gelo envolve seus pés.",
  "Um raio de luz divina desce do céu.",
  "Você é teletransportado alguns metros para o lado.",
  "As runas antigas brilham na sua pele.",

  // Novas frases adicionadas
  "Um véu de sombras obscurece a visão ao redor.",
  "Você sente os ventos do destino soprar a seu favor.",
  "As estrelas alinham-se em padrões desconhecidos.",
  "Uma onda de energia psíquica percorre seu corpo.",
  "Pequenas chamas dançam sobre seus ombros.",
  "Um eco de vozes antigas sussurra segredos.",
  "A terra treme levemente sob seus pés.",
  "Um campo de força envolve você por instantes.",
  "Você ouve o rugido distante de criaturas ancestrais.",
  "Uma chuva de partículas cintilantes cobre o ambiente.",
  "Seus olhos brilham com luz própria.",
  "Um círculo mágico se forma ao seu redor.",
  "Um lobo etéreo aparece ao seu lado.",
  "Você sente o toque do tempo em sua mão.",
  "Pequenas faíscas elétricas percorrem seus braços.",
  "Uma névoa fantasmagórica envolve a área.",
  "Uma espada de energia se materializa em suas mãos.",
  "O ar vibra com energia desconhecida.",
  "Uma aura dourada envolve seus aliados próximos.",
  "Você sente a presença de espíritos antigos.",
  "Uma explosão de cores mágicas se manifesta ao seu redor.",
  "Sombras dançam em padrões inquietantes.",
  "Você é envolto em correntes de luz e escuridão.",
  "Um brilho sobrenatural irradia do chão.",
  "Você sente forças invisíveis guiando seus passos.",
  "Um trovão silencioso ressoa pelo ambiente.",
  "Um feitiço de proteção envolve todos ao seu redor.",
  "Você vislumbra visões de outras dimensões.",
  "O vento sussurra palavras antigas em sua mente.",
  "Um arco de energia se forma entre suas mãos.",
  "A água ao redor começa a brilhar com magia.",
  "Pequenas criaturas mágicas aparecem momentaneamente.",
  "O chão se ilumina com símbolos ancestrais.",
  "Um fluxo de energia percorre o ar como um rio.",
  "Você sente os elementos responderem à sua vontade.",
  "Uma ponte de luz conecta dois pontos distantes.",
  "Um feitiço de invisibilidade envolve você brevemente.",
  "As chamas mágicas dançam em ritmo próprio.",
  "Um brilho prateado percorre o ambiente.",
  "Você ouve ecos do passado reverberando ao redor.",
  "Pequenas runas flutuam no ar em círculos.",
  "Uma onda de calma e serenidade toma conta do espaço.",
  "Você sente uma conexão com o cosmos.",
  "Um redemoinho de energia forma-se sob seus pés.",
  "As paredes do ambiente parecem vibrar levemente.",
  "Uma esfera de luz flutua diante de você.",
  "Você sente a força da natureza ao seu redor.",
  "Um portal reluzente aparece e desaparece rapidamente.",
  "Sombras sutis se movem em padrões enigmáticos.",
  "Uma chuva de estrelas cadentes cobre o céu imaginário.",
  "Você sente seu poder interior se intensificar.",
];
